export const AVAILABLE_SUBJECTS = [
  "Mathematics",
  "Algebra",
  "Geometry",
  "Trigonometry",
  "Calculus",
  "Statistics",
  "Physics",
  "Chemistry",
  "Biology",
  "English",
  "Literature",
  "Writing",
  "Grammar",
  "History",
  "Geography",
  "Computer Science",
  "Economics",
  "Psychology",
  "Spanish",
  "French",
  "German",
  "Arabic",
  "GCSE Mathematics",
  "A-Level Mathematics",
  "Numeracy Tests",
  "SAT Mathematics",
  "ACT Mathematics",
];

